### ISSUE TITLE
An error occured while opening the save file: Header is in an invalid format when trying to open save from Nintendo Switch

### ISSUE THREAD

**Issue by Rafario448** [aldelaro5/Bug-Fables-Save-Editor#5]
I get the error mentioned in the tittle when trying to open the save from the nintendo switch version

Here's the link of the save
https://drive.google.com/file/d/1Uhx9_Cn2ESNqgz5R5Ralx7WDo_2AXIao/view?usp=sharing

**Comment by aldelaro5** [comment]
The save editor currently does not support switch saves.

However, I happened to have a softmodable switch and I was planning to implement this whenever I come back to this game (which is not soon btw, I am aiming sometime this year, but can't guarantee).

So I will label this as enhancement, keep your save there because I actually need that to properly implement it whenever possible.

**Comment by WACOMalt** [comment]
Just want to chime in that I would love this. I had hoped to use the tool to convert a Switch save to a PC save. Seems that only the headers of the files are different.

**Comment by aldelaro5** [comment]
I definitely should implement platform conversions yeah, tbh the save editor is probably going to be the first thing I work on once I come back to this game because I already had ideas of other improvements already and these aren't hard to do.

So far, I ETA to be back in the community around fall, but that may change. You'll probably know more when that happens if you are in the discord, but I'll update this whenever this is implemented.

**Comment by aldelaro5** [comment]
Switch save format is supported as of 1.0.0
